- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:jasonhightower/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./run-stow
  tags:
    - install
    - dotfiles
    - stow

  #- name: AEPP Exists
  #  stat:
  #    path: "{{ target_dir }}aepp"
  #  register: aepp
  #  tags:
  #    - install
  #    - cmle
  #- name: AEP Platform API made for humans
  #  ansible.builtin.git:
  #    repo: 'git@github.com:pitchmuc/aepp.git'
  #    dest: "{{ target_dir }}aepp"
  #    accept_hostkey: yes
  #  tags:
  #    - install
  #    - cmle
  #  when: aepp.stat.exists == False
