- name: Ensure .ssh directory exists
  file:
    dest: "{{ dest_key_dir | dirname }}"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh
    - dotfiles
- name: Install ssh keys
  copy: 
    src: "{{ item }}"
    dest: "{{ dest_key_dir }}"
    mode: 0600
  with_fileglob:
    - "{{ source_key_dir }}*"
  tags:
    - install
    - ssh
    - dotfiles
# TODO need to chmod 0644 *.pub
- name: Set authorized keys
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ dest_key_dir }}*.pub"
  tags:
    - install
    - ssh
    - dotfiles
