- name: Install zsh
  package: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'dotfiles', 'zsh' ]

# - name: Change shell to zsh
#  vars:
#    the_user: "{{ ansible_user_id }}"
#  tasks:
#    - name: change shell to zsh
#      become: yes
#      user:
#        name: "{{ the_user }}"
#        shell: /opt/homebrew/bin/zsh

- name: Check if oh-my-zsh is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Install oh-my-zsh
  shell: curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
#  become_user: jasonh
